#!/usr/bin/env python3

import argparse

def listSplit(array, separator):
    splitIndices = [-1]+[i for i in range(len(array)) if array[i]==separator] #define slice points
    slicedArray = [array[1+splitIndices[i]:splitIndices[i+1]] for i in range(len(splitIndices)-1)]
    return slicedArray

def lineMunge(line, index):
    if not index:
        #leading line of pattern: leading string is "    pattern {", elements are unquoted
        s = ', '.join(line.split(','))
        return f"    pattern {{{s}}}"
    else:
        #other lines: leading string is 12 spaces, elements are quoted
        s = ', '.join([f'\"{i}\"' for i in line.split(',')])
        return f"            {{{s}}}"

def patternMunge(pattern):
    return "\n".join([lineMunge(pattern[i], i) for i in range(len(pattern))])

def csvMunge(fname, dbname):
    dbLeading = f"file \"{dbname}\""
    lines = [i.strip(',') for i in open(fname).read().split("\n")]
    patternArrays = listSplit(lines, '')
    patterns = [patternMunge(i) for i in patternArrays]
    return f"{dbLeading}{{\n{'\n'.join(patterns)}\n}}"

def main():
    parser = argparse.ArgumentParser(description="Munge CSV files into an EPICS compatible substitution file")
    parser.add_argument("fname", nargs="*", help="Files to be munged")
    parser.add_argument("-d", "--database", help="Database files being substituted. Paths relative to IOC top. Default: db/fname.db for all input files", nargs="*") #Maybe change to paths relative to $(TOP)/db?
    parser.add_argument("-o", "--output", help="Output file. If unspecified, each fname munges into separate fname.substitutions", nargs='?')
    args = parser.parse_args()

    dbs = []
    for i in range(len(args.fname)):
        if(not args.database or i>=len(args(database))): #non-commutative logical or; inverting this causes an error
            x = csvMunge(args.fname[i], f'db/{args.fname[i][:-4]}.db')
        else:
            x = csvMunge(args.fname[i], args.database[i])
        dbs.append(x)
    print("\n\n".join(dbs))

if(__name__=="__main__"):
    main()
