#!/usr/bin/env python3

import argparse, os, sys, re

def listSplit(array, separator):
    # split an array based on a separator element - replicating string.split for arrays
    splitIndices = [-1]+[i for i in range(len(array)) if array[i]==separator] # define slice points
    slicedArray = [array[1+splitIndices[i]:splitIndices[i+1]] for i in range(len(splitIndices)-1)]
    return slicedArray

def lineMunge(line, index, length):
    if line[0]=="#":
        return f"{12*" "}{line}"
    if not index:
        # leading line of pattern: leading string is "    pattern {", elements are unquoted
        s = ', '.join(line.split(',')[:length])
        return f"{4*" "}pattern {{ {s} }}"
    else:
        # other lines: leading string is 12 spaces, elements are optionally quoted
        s = ', '.join([(f'\"{i}\"' if(not len(i) or args.quotes or re.search(r'\s', i)) else i) for i in line.split(',')[:length]])
        return f"{12*" "}{{ {s} }}"

def patternMunge(pattern):
    leading = f"file \"{pattern[0].rstrip(',')}\" {{"
    trailing = "}"
    pattLength = len(pattern[1].rstrip(',').split(','))
    return "\n".join([leading] + [lineMunge(pattern[i], i-1, pattLength) for i in range(1, len(pattern))] + [trailing]) # munges each pattern line and joins them into a string

def csvMunge(fname):
    with open(fname, "r") as inFile:
        lines = [i.lstrip(',') for i in inFile.read().split("\n")] # strip all lines of leading commas to detect empty lines
    patterns = [patternMunge(i) for i in listSplit(lines, '')]
    return '\n\n'.join(patterns)

def main():

    # ingest arguments from command line
    parser = argparse.ArgumentParser(description="Munge CSV files into an EPICS compatible substitution file")
    parser.add_argument("FNAME", nargs="+", help="Files to be munged")
    parser.add_argument("-f", "--force", help="Overwrite existing files. If unspecified, attempting to output to an existing file throws an error.", action="store_true")
    parser.add_argument("-q", "--quotes", help="Surround substitutes in quotes. Empty elements and elements with whitespace will always be quoted.", action="store_true")
    parser.add_argument("-o", "--output", help="Output file. If unspecified, each fname munges into separate fname.substitutions", nargs='?')
    global args
    args = parser.parse_args()

    nFiles = len(args.FNAME)
    fnameBases = [(i.split('.')[-2] if '.' in i else i) for i in args.FNAME]

    # handle existing files
    outputFiles = [args.output] if args.output else [f"{i}.substitutions" for i in fnameBases]
    if (not args.force and any([os.path.exists(i) for i in outputFiles])):
        print(
            f"Error: File '{[i for i in outputFiles if os.path.exists(i)][0]}' already exists in the current directory. Pass -f to overwrite.",
            file=sys.stderr,
        )
        sys.exit(1)

    # munge CSVs
    dbs = [csvMunge(i) for i in args.FNAME]

    # handle output
    if args.output:
        outString = "\n\n".join(dbs)
        with open(args.output, "w") as outFile:
            outFile.write(outString)
    else:
        for i in range(nFiles):
            with open(outputFiles[i], "w") as outFile:
                outFile.write(dbs[i])

if(__name__=="__main__"):
    main()
